import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import Logo from "@/app/components/logo";
import { Provider } from "./components/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider >
          <div className="grid bg-white grid-cols-2 gap-2 sticky top-0 z-[20]">
            <Logo />
          </div>
          <Header />
          {children}
        </Provider></body>
    </html>
  );
}
